name: "Powerup USB monitor"
description: "Monitor Direct USB connection for UPS data"
version: "1.1.8"
slug: "powerup_upsmon"
init: false
startup: application
boot: auto
services:
  - "mqtt:need"
devices:
  - "/dev/hidraw0"
  - "/dev/hidraw1"
  - "/dev/hidraw2"
options:
  Inverter_device: "/dev/hidraw0"
  Log_level: "INFO"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
schema:
  Inverter_device: str
  Log_level: "list(INFO|WARNING|ERROR|DEBUG)"
